### ISSUE TITLE
Controller intermittently fails to authenticate with home assistant

### ISSUE THREAD

**Issue by ccontour** [ccontour/steggy#101]
Observed happening ~5% of the time, logs typically end roughly here -

```
{"level":30,"time":1648137419398,"pid":1,"hostname":"8fcd367ebeac","context":"boilerplate:Bootstrap","msg":"🎓 Bootstrap control released! 🎓"}
{"level":30,"time":1648137419398,"pid":1,"hostname":"8fcd367ebeac","context":"server:MiddlewareService","msg":"📡 Listening on [7000] {(http)} 📡"}
{"level":20,"time":1648137419445,"pid":1,"hostname":"8fcd367ebeac","context":"home-assistant:HASocketAPIService","msg":"Sending auth"}
{"level":20,"time":1648137419449,"pid":1,"hostname":"8fcd367ebeac","context":"home-assistant:HASocketAPIService","msg":"[CONNECTION_ACTIVE] = {true}"}
```

Where the last attempted action was "sending auth". Does not proceed to retrieving entity lists, and mounting routines. Most easily resolved by restarting the server.

Introduce some sort of short retry timeout to attempt to identify stalled auth requests like this, and retry

**Comment by ccontour** [comment]
Used `libs.home_assistant.RETRY_INTERVAL` as "waited too long" timeout. If auth response not received, a retry will occur + emit error log

Closing ticket when I see this actually happen, make sure it works as intended

**Comment by ccontour** [comment]
Added retry to load all entities calls also

**Comment by ccontour** [comment]
Leaving issue open, there still seems to be some sort of intermittent issue or race condition happening around the entity refresh. Especially the first refresh to load all entities, which prevents the completion of the bootstrap process for the server.

Manually restarting seems fine, but automated retries seem to not be solving the issue so far.

**Comment by ccontour** [comment]
Observation: Node process increases to 100% cpu and stays pinned when this happens

**Comment by ccontour** [comment]
https://github.com/ccontour/steggy/blob/0.9.13/libs/home-assistant/src/services/ha-socket-api.service.ts#L75

**Comment by ccontour** [comment]
### New working theory

The subscribe to events command is sent prior to the update all entities command. Occasionally, a race condition occurs where an entity update is received prior to that entity being "officially loaded". 

### New attempt at fix

Adjust the subscription to happen after the first entity update of a given connection

**Comment by ccontour** [comment]
Fix seems to be working. Resolved with `9.0.14`

**Comment by ccontour** [comment]
Happened again

**Comment by ccontour** [comment]
Added the ability to see all incoming socket messages from home assistant by setting log level to `trace`. It's quite spammy, so keeping it out of the regular debug logs. This race condition seems to never happen when that message is enabled 🤔

Currently testing solutions:

- magic 50ms sleep inside `getAllEntities`
- moving first `initConnection` call from `onApplicationBootstrap` to `onPostInit`

**Comment by ccontour** [comment]
Observed in `0.11.x`. Last log message
```
[home-assistant:HASocketAPIService] Sending get_states
```

**Comment by mp3three** [comment]
Issue still persists, but interesting observation: 

When this is affecting the dev server, it is possible to save and reload the controller. The previous instance will stick around, holding on to the web port. (`fuser -k 7000/tcp` can terminate, assuming default port). This error gets emitted part way through boot:

```
Error
listen EADDRINUSE: address already in use :::7000
Error: listen EADDRINUSE: address already in use :::7000
    at Server.setupListenHandle [as _listen2] (node:net:1414:16)
    at listenInCluster (node:net:1462:12)
    at Server.listen (node:net:1550:7)
```
Ignoring the situation though, and attempting to send http requests through results in an error indicating the mongo client isn't connected. Need to look into the database somehow being the root cause of this headache
